/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as GuiaVistoH2bRouteImport } from './routes/guia-visto-h2b'
import { Route as GuiaSalarioH2aRouteImport } from './routes/guia-salario-h2a'
import { Route as GuiaH2aVsH2bRouteImport } from './routes/guia-h2a-vs-h2b'
import { Route as GuiaGolpesH2aRouteImport } from './routes/guia-golpes-h2a'
import { Route as GuiaEntrevistaVistoH2aRouteImport } from './routes/guia-entrevista-visto-h2a'
import { Route as GuiaDs160VistoH2aRouteImport } from './routes/guia-ds160-visto-h2a'
import { Route as GuiaCustosVistoH2aRouteImport } from './routes/guia-custos-visto-h2a'
import { Route as ComoTrabalharNosEuaLegalmenteRouteImport } from './routes/como-trabalhar-nos-eua-legalmente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasH2aIndexRouteImport } from './routes/vagas-h2a.index'
import { Route as VagasH2aTabacoRouteImport } from './routes/vagas-h2a.tabaco'
import { Route as VagasH2aEmpresasRouteImport } from './routes/vagas-h2a.empresas'
import { Route as VagasH2aColheitaMacaRouteImport } from './routes/vagas-h2a.colheita-maca'
import { Route as VagasH2aColheitaLaranjaRouteImport } from './routes/vagas-h2a.colheita-laranja'
import { Route as VagasH2aStateRouteImport } from './routes/vagas-h2a.$state'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedAppVistoRouteImport } from './routes/_authenticated/app.visto'
import { Route as AuthenticatedAppVideoRouteImport } from './routes/_authenticated/app.video'
import { Route as AuthenticatedAppVagasRouteImport } from './routes/_authenticated/app.vagas'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppMidiaRouteImport } from './routes/_authenticated/app.midia'
import { Route as AuthenticatedAppInglesRouteImport } from './routes/_authenticated/app.ingles'
import { Route as AuthenticatedAppFollowupsRouteImport } from './routes/_authenticated/app.followups'
import { Route as AuthenticatedAppEmpregadoresRouteImport } from './routes/_authenticated/app.empregadores'
import { Route as AuthenticatedAppCurriculosRouteImport } from './routes/_authenticated/app.curriculos'
import { Route as AuthenticatedAppCurriculoRouteImport } from './routes/_authenticated/app.curriculo'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppComecarRouteImport } from './routes/_authenticated/app.comecar'
import { Route as AuthenticatedAppCandidaturasRouteImport } from './routes/_authenticated/app.candidaturas'
import { Route as AuthenticatedAppAuditoriaRouteImport } from './routes/_authenticated/app.auditoria'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminSecurityRouteImport } from './routes/_authenticated/admin.security'
import { Route as AuthenticatedAdminProFeaturesRouteImport } from './routes/_authenticated/admin.pro-features'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAppInglesIndexRouteImport } from './routes/_authenticated/app.ingles.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsDevSelftestRouteImport } from './routes/api/public/payments/dev-selftest'
import { Route as ApiPublicHooksVisaRemindersRouteImport } from './routes/api/public/hooks/visa-reminders'
import { Route as ApiPublicHooksUptimeRouteImport } from './routes/api/public/hooks/uptime'
import { Route as ApiPublicHooksSpikeAlertRouteImport } from './routes/api/public/hooks/spike-alert'
import { Route as ApiPublicHooksSeoScanRouteImport } from './routes/api/public/hooks/seo-scan'
import { Route as ApiPublicHooksImportDolFeedRouteImport } from './routes/api/public/hooks/import-dol-feed'
import { Route as ApiPublicHooksCheckRepliesRouteImport } from './routes/api/public/hooks/check-replies'
import { Route as AuthenticatedAppVistoHistoricoRouteImport } from './routes/_authenticated/app.visto.historico'
import { Route as AuthenticatedAppInglesModuleRouteImport } from './routes/_authenticated/app.ingles.$module'
import { Route as AuthenticatedAppAdminEmailsRouteImport } from './routes/_authenticated/app.admin.emails'
import { Route as AuthenticatedAppInglesModuleIndexRouteImport } from './routes/_authenticated/app.ingles.$module.index'
import { Route as AuthenticatedAppInglesModuleLessonRouteImport } from './routes/_authenticated/app.ingles.$module.$lesson'
import { Route as AuthenticatedAppAdminEmailsPreviewRouteImport } from './routes/_authenticated/app.admin.emails.preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaVistoH2bRoute = GuiaVistoH2bRouteImport.update({
  id: '/guia-visto-h2b',
  path: '/guia-visto-h2b',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSalarioH2aRoute = GuiaSalarioH2aRouteImport.update({
  id: '/guia-salario-h2a',
  path: '/guia-salario-h2a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaH2aVsH2bRoute = GuiaH2aVsH2bRouteImport.update({
  id: '/guia-h2a-vs-h2b',
  path: '/guia-h2a-vs-h2b',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaGolpesH2aRoute = GuiaGolpesH2aRouteImport.update({
  id: '/guia-golpes-h2a',
  path: '/guia-golpes-h2a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaEntrevistaVistoH2aRoute = GuiaEntrevistaVistoH2aRouteImport.update({
  id: '/guia-entrevista-visto-h2a',
  path: '/guia-entrevista-visto-h2a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDs160VistoH2aRoute = GuiaDs160VistoH2aRouteImport.update({
  id: '/guia-ds160-visto-h2a',
  path: '/guia-ds160-visto-h2a',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaCustosVistoH2aRoute = GuiaCustosVistoH2aRouteImport.update({
  id: '/guia-custos-visto-h2a',
  path: '/guia-custos-visto-h2a',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabalharNosEuaLegalmenteRoute =
  ComoTrabalharNosEuaLegalmenteRouteImport.update({
    id: '/como-trabalhar-nos-eua-legalmente',
    path: '/como-trabalhar-nos-eua-legalmente',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aIndexRoute = VagasH2aIndexRouteImport.update({
  id: '/vagas-h2a/',
  path: '/vagas-h2a/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aTabacoRoute = VagasH2aTabacoRouteImport.update({
  id: '/vagas-h2a/tabaco',
  path: '/vagas-h2a/tabaco',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aEmpresasRoute = VagasH2aEmpresasRouteImport.update({
  id: '/vagas-h2a/empresas',
  path: '/vagas-h2a/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aColheitaMacaRoute = VagasH2aColheitaMacaRouteImport.update({
  id: '/vagas-h2a/colheita-maca',
  path: '/vagas-h2a/colheita-maca',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aColheitaLaranjaRoute = VagasH2aColheitaLaranjaRouteImport.update({
  id: '/vagas-h2a/colheita-laranja',
  path: '/vagas-h2a/colheita-laranja',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aStateRoute = VagasH2aStateRouteImport.update({
  id: '/vagas-h2a/$state',
  path: '/vagas-h2a/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVistoRoute = AuthenticatedAppVistoRouteImport.update({
  id: '/app/visto',
  path: '/app/visto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVideoRoute = AuthenticatedAppVideoRouteImport.update({
  id: '/app/video',
  path: '/app/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVagasRoute = AuthenticatedAppVagasRouteImport.update({
  id: '/app/vagas',
  path: '/app/vagas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMidiaRoute = AuthenticatedAppMidiaRouteImport.update({
  id: '/app/midia',
  path: '/app/midia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppInglesRoute = AuthenticatedAppInglesRouteImport.update({
  id: '/app/ingles',
  path: '/app/ingles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFollowupsRoute =
  AuthenticatedAppFollowupsRouteImport.update({
    id: '/app/followups',
    path: '/app/followups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmpregadoresRoute =
  AuthenticatedAppEmpregadoresRouteImport.update({
    id: '/app/empregadores',
    path: '/app/empregadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCurriculosRoute =
  AuthenticatedAppCurriculosRouteImport.update({
    id: '/app/curriculos',
    path: '/app/curriculos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCurriculoRoute =
  AuthenticatedAppCurriculoRouteImport.update({
    id: '/app/curriculo',
    path: '/app/curriculo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/app/configuracoes',
    path: '/app/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComecarRoute = AuthenticatedAppComecarRouteImport.update({
  id: '/app/comecar',
  path: '/app/comecar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCandidaturasRoute =
  AuthenticatedAppCandidaturasRouteImport.update({
    id: '/app/candidaturas',
    path: '/app/candidaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditoriaRoute =
  AuthenticatedAppAuditoriaRouteImport.update({
    id: '/app/auditoria',
    path: '/app/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSecurityRoute =
  AuthenticatedAdminSecurityRouteImport.update({
    id: '/admin/security',
    path: '/admin/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProFeaturesRoute =
  AuthenticatedAdminProFeaturesRouteImport.update({
    id: '/admin/pro-features',
    path: '/admin/pro-features',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/admin/onboarding',
    path: '/admin/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInglesIndexRoute =
  AuthenticatedAppInglesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInglesRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsDevSelftestRoute =
  ApiPublicPaymentsDevSelftestRouteImport.update({
    id: '/api/public/payments/dev-selftest',
    path: '/api/public/payments/dev-selftest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksVisaRemindersRoute =
  ApiPublicHooksVisaRemindersRouteImport.update({
    id: '/api/public/hooks/visa-reminders',
    path: '/api/public/hooks/visa-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUptimeRoute = ApiPublicHooksUptimeRouteImport.update({
  id: '/api/public/hooks/uptime',
  path: '/api/public/hooks/uptime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSpikeAlertRoute =
  ApiPublicHooksSpikeAlertRouteImport.update({
    id: '/api/public/hooks/spike-alert',
    path: '/api/public/hooks/spike-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSeoScanRoute = ApiPublicHooksSeoScanRouteImport.update({
  id: '/api/public/hooks/seo-scan',
  path: '/api/public/hooks/seo-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksImportDolFeedRoute =
  ApiPublicHooksImportDolFeedRouteImport.update({
    id: '/api/public/hooks/import-dol-feed',
    path: '/api/public/hooks/import-dol-feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckRepliesRoute =
  ApiPublicHooksCheckRepliesRouteImport.update({
    id: '/api/public/hooks/check-replies',
    path: '/api/public/hooks/check-replies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppVistoHistoricoRoute =
  AuthenticatedAppVistoHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedAppVistoRoute,
  } as any)
const AuthenticatedAppInglesModuleRoute =
  AuthenticatedAppInglesModuleRouteImport.update({
    id: '/$module',
    path: '/$module',
    getParentRoute: () => AuthenticatedAppInglesRoute,
  } as any)
const AuthenticatedAppAdminEmailsRoute =
  AuthenticatedAppAdminEmailsRouteImport.update({
    id: '/app/admin/emails',
    path: '/app/admin/emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInglesModuleIndexRoute =
  AuthenticatedAppInglesModuleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInglesModuleRoute,
  } as any)
const AuthenticatedAppInglesModuleLessonRoute =
  AuthenticatedAppInglesModuleLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => AuthenticatedAppInglesModuleRoute,
  } as any)
const AuthenticatedAppAdminEmailsPreviewRoute =
  AuthenticatedAppAdminEmailsPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAppAdminEmailsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-trabalhar-nos-eua-legalmente': typeof ComoTrabalharNosEuaLegalmenteRoute
  '/guia-custos-visto-h2a': typeof GuiaCustosVistoH2aRoute
  '/guia-ds160-visto-h2a': typeof GuiaDs160VistoH2aRoute
  '/guia-entrevista-visto-h2a': typeof GuiaEntrevistaVistoH2aRoute
  '/guia-golpes-h2a': typeof GuiaGolpesH2aRoute
  '/guia-h2a-vs-h2b': typeof GuiaH2aVsH2bRoute
  '/guia-salario-h2a': typeof GuiaSalarioH2aRoute
  '/guia-visto-h2b': typeof GuiaVistoH2bRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a/colheita-laranja': typeof VagasH2aColheitaLaranjaRoute
  '/vagas-h2a/colheita-maca': typeof VagasH2aColheitaMacaRoute
  '/vagas-h2a/empresas': typeof VagasH2aEmpresasRoute
  '/vagas-h2a/tabaco': typeof VagasH2aTabacoRoute
  '/vagas-h2a/': typeof VagasH2aIndexRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pro-features': typeof AuthenticatedAdminProFeaturesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/comecar': typeof AuthenticatedAppComecarRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/app/curriculos': typeof AuthenticatedAppCurriculosRoute
  '/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/ingles': typeof AuthenticatedAppInglesRouteWithChildren
  '/app/midia': typeof AuthenticatedAppMidiaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app/video': typeof AuthenticatedAppVideoRoute
  '/app/visto': typeof AuthenticatedAppVistoRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/emails': typeof AuthenticatedAppAdminEmailsRouteWithChildren
  '/app/ingles/$module': typeof AuthenticatedAppInglesModuleRouteWithChildren
  '/app/visto/historico': typeof AuthenticatedAppVistoHistoricoRoute
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
  '/api/public/hooks/spike-alert': typeof ApiPublicHooksSpikeAlertRoute
  '/api/public/hooks/uptime': typeof ApiPublicHooksUptimeRoute
  '/api/public/hooks/visa-reminders': typeof ApiPublicHooksVisaRemindersRoute
  '/api/public/payments/dev-selftest': typeof ApiPublicPaymentsDevSelftestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/ingles/': typeof AuthenticatedAppInglesIndexRoute
  '/app/admin/emails/preview': typeof AuthenticatedAppAdminEmailsPreviewRoute
  '/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/app/ingles/$module/': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-trabalhar-nos-eua-legalmente': typeof ComoTrabalharNosEuaLegalmenteRoute
  '/guia-custos-visto-h2a': typeof GuiaCustosVistoH2aRoute
  '/guia-ds160-visto-h2a': typeof GuiaDs160VistoH2aRoute
  '/guia-entrevista-visto-h2a': typeof GuiaEntrevistaVistoH2aRoute
  '/guia-golpes-h2a': typeof GuiaGolpesH2aRoute
  '/guia-h2a-vs-h2b': typeof GuiaH2aVsH2bRoute
  '/guia-salario-h2a': typeof GuiaSalarioH2aRoute
  '/guia-visto-h2b': typeof GuiaVistoH2bRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a/colheita-laranja': typeof VagasH2aColheitaLaranjaRoute
  '/vagas-h2a/colheita-maca': typeof VagasH2aColheitaMacaRoute
  '/vagas-h2a/empresas': typeof VagasH2aEmpresasRoute
  '/vagas-h2a/tabaco': typeof VagasH2aTabacoRoute
  '/vagas-h2a': typeof VagasH2aIndexRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/pro-features': typeof AuthenticatedAdminProFeaturesRoute
  '/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/comecar': typeof AuthenticatedAppComecarRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/app/curriculos': typeof AuthenticatedAppCurriculosRoute
  '/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/midia': typeof AuthenticatedAppMidiaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app/video': typeof AuthenticatedAppVideoRoute
  '/app/visto': typeof AuthenticatedAppVistoRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/emails': typeof AuthenticatedAppAdminEmailsRouteWithChildren
  '/app/visto/historico': typeof AuthenticatedAppVistoHistoricoRoute
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
  '/api/public/hooks/spike-alert': typeof ApiPublicHooksSpikeAlertRoute
  '/api/public/hooks/uptime': typeof ApiPublicHooksUptimeRoute
  '/api/public/hooks/visa-reminders': typeof ApiPublicHooksVisaRemindersRoute
  '/api/public/payments/dev-selftest': typeof ApiPublicPaymentsDevSelftestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/ingles': typeof AuthenticatedAppInglesIndexRoute
  '/app/admin/emails/preview': typeof AuthenticatedAppAdminEmailsPreviewRoute
  '/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/app/ingles/$module': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/como-trabalhar-nos-eua-legalmente': typeof ComoTrabalharNosEuaLegalmenteRoute
  '/guia-custos-visto-h2a': typeof GuiaCustosVistoH2aRoute
  '/guia-ds160-visto-h2a': typeof GuiaDs160VistoH2aRoute
  '/guia-entrevista-visto-h2a': typeof GuiaEntrevistaVistoH2aRoute
  '/guia-golpes-h2a': typeof GuiaGolpesH2aRoute
  '/guia-h2a-vs-h2b': typeof GuiaH2aVsH2bRoute
  '/guia-salario-h2a': typeof GuiaSalarioH2aRoute
  '/guia-visto-h2b': typeof GuiaVistoH2bRoute
  '/precos': typeof PrecosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a/colheita-laranja': typeof VagasH2aColheitaLaranjaRoute
  '/vagas-h2a/colheita-maca': typeof VagasH2aColheitaMacaRoute
  '/vagas-h2a/empresas': typeof VagasH2aEmpresasRoute
  '/vagas-h2a/tabaco': typeof VagasH2aTabacoRoute
  '/vagas-h2a/': typeof VagasH2aIndexRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/pro-features': typeof AuthenticatedAdminProFeaturesRoute
  '/_authenticated/admin/security': typeof AuthenticatedAdminSecurityRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/app/auditoria': typeof AuthenticatedAppAuditoriaRoute
  '/_authenticated/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/_authenticated/app/comecar': typeof AuthenticatedAppComecarRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/_authenticated/app/curriculos': typeof AuthenticatedAppCurriculosRoute
  '/_authenticated/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/_authenticated/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/_authenticated/app/ingles': typeof AuthenticatedAppInglesRouteWithChildren
  '/_authenticated/app/midia': typeof AuthenticatedAppMidiaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/vagas': typeof AuthenticatedAppVagasRoute
  '/_authenticated/app/video': typeof AuthenticatedAppVideoRoute
  '/_authenticated/app/visto': typeof AuthenticatedAppVistoRouteWithChildren
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/emails': typeof AuthenticatedAppAdminEmailsRouteWithChildren
  '/_authenticated/app/ingles/$module': typeof AuthenticatedAppInglesModuleRouteWithChildren
  '/_authenticated/app/visto/historico': typeof AuthenticatedAppVistoHistoricoRoute
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/api/public/hooks/seo-scan': typeof ApiPublicHooksSeoScanRoute
  '/api/public/hooks/spike-alert': typeof ApiPublicHooksSpikeAlertRoute
  '/api/public/hooks/uptime': typeof ApiPublicHooksUptimeRoute
  '/api/public/hooks/visa-reminders': typeof ApiPublicHooksVisaRemindersRoute
  '/api/public/payments/dev-selftest': typeof ApiPublicPaymentsDevSelftestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/ingles/': typeof AuthenticatedAppInglesIndexRoute
  '/_authenticated/app/admin/emails/preview': typeof AuthenticatedAppAdminEmailsPreviewRoute
  '/_authenticated/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/_authenticated/app/ingles/$module/': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/como-trabalhar-nos-eua-legalmente'
    | '/guia-custos-visto-h2a'
    | '/guia-ds160-visto-h2a'
    | '/guia-entrevista-visto-h2a'
    | '/guia-golpes-h2a'
    | '/guia-h2a-vs-h2b'
    | '/guia-salario-h2a'
    | '/guia-visto-h2b'
    | '/precos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a/colheita-laranja'
    | '/vagas-h2a/colheita-maca'
    | '/vagas-h2a/empresas'
    | '/vagas-h2a/tabaco'
    | '/vagas-h2a/'
    | '/admin/onboarding'
    | '/admin/pro-features'
    | '/admin/security'
    | '/admin/seo'
    | '/app/auditoria'
    | '/app/candidaturas'
    | '/app/comecar'
    | '/app/configuracoes'
    | '/app/curriculo'
    | '/app/curriculos'
    | '/app/empregadores'
    | '/app/followups'
    | '/app/ingles'
    | '/app/midia'
    | '/app/perfil'
    | '/app/vagas'
    | '/app/video'
    | '/app/visto'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/app/'
    | '/app/admin/emails'
    | '/app/ingles/$module'
    | '/app/visto/historico'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/api/public/hooks/seo-scan'
    | '/api/public/hooks/spike-alert'
    | '/api/public/hooks/uptime'
    | '/api/public/hooks/visa-reminders'
    | '/api/public/payments/dev-selftest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/ingles/'
    | '/app/admin/emails/preview'
    | '/app/ingles/$module/$lesson'
    | '/app/ingles/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/como-trabalhar-nos-eua-legalmente'
    | '/guia-custos-visto-h2a'
    | '/guia-ds160-visto-h2a'
    | '/guia-entrevista-visto-h2a'
    | '/guia-golpes-h2a'
    | '/guia-h2a-vs-h2b'
    | '/guia-salario-h2a'
    | '/guia-visto-h2b'
    | '/precos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a/colheita-laranja'
    | '/vagas-h2a/colheita-maca'
    | '/vagas-h2a/empresas'
    | '/vagas-h2a/tabaco'
    | '/vagas-h2a'
    | '/admin/onboarding'
    | '/admin/pro-features'
    | '/admin/security'
    | '/admin/seo'
    | '/app/auditoria'
    | '/app/candidaturas'
    | '/app/comecar'
    | '/app/configuracoes'
    | '/app/curriculo'
    | '/app/curriculos'
    | '/app/empregadores'
    | '/app/followups'
    | '/app/midia'
    | '/app/perfil'
    | '/app/vagas'
    | '/app/video'
    | '/app/visto'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/app'
    | '/app/admin/emails'
    | '/app/visto/historico'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/api/public/hooks/seo-scan'
    | '/api/public/hooks/spike-alert'
    | '/api/public/hooks/uptime'
    | '/api/public/hooks/visa-reminders'
    | '/api/public/payments/dev-selftest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/ingles'
    | '/app/admin/emails/preview'
    | '/app/ingles/$module/$lesson'
    | '/app/ingles/$module'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/como-trabalhar-nos-eua-legalmente'
    | '/guia-custos-visto-h2a'
    | '/guia-ds160-visto-h2a'
    | '/guia-entrevista-visto-h2a'
    | '/guia-golpes-h2a'
    | '/guia-h2a-vs-h2b'
    | '/guia-salario-h2a'
    | '/guia-visto-h2b'
    | '/precos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a/colheita-laranja'
    | '/vagas-h2a/colheita-maca'
    | '/vagas-h2a/empresas'
    | '/vagas-h2a/tabaco'
    | '/vagas-h2a/'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/pro-features'
    | '/_authenticated/admin/security'
    | '/_authenticated/admin/seo'
    | '/_authenticated/app/auditoria'
    | '/_authenticated/app/candidaturas'
    | '/_authenticated/app/comecar'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/curriculo'
    | '/_authenticated/app/curriculos'
    | '/_authenticated/app/empregadores'
    | '/_authenticated/app/followups'
    | '/_authenticated/app/ingles'
    | '/_authenticated/app/midia'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/vagas'
    | '/_authenticated/app/video'
    | '/_authenticated/app/visto'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/emails'
    | '/_authenticated/app/ingles/$module'
    | '/_authenticated/app/visto/historico'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/api/public/hooks/seo-scan'
    | '/api/public/hooks/spike-alert'
    | '/api/public/hooks/uptime'
    | '/api/public/hooks/visa-reminders'
    | '/api/public/payments/dev-selftest'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/ingles/'
    | '/_authenticated/app/admin/emails/preview'
    | '/_authenticated/app/ingles/$module/$lesson'
    | '/_authenticated/app/ingles/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ComoTrabalharNosEuaLegalmenteRoute: typeof ComoTrabalharNosEuaLegalmenteRoute
  GuiaCustosVistoH2aRoute: typeof GuiaCustosVistoH2aRoute
  GuiaDs160VistoH2aRoute: typeof GuiaDs160VistoH2aRoute
  GuiaEntrevistaVistoH2aRoute: typeof GuiaEntrevistaVistoH2aRoute
  GuiaGolpesH2aRoute: typeof GuiaGolpesH2aRoute
  GuiaH2aVsH2bRoute: typeof GuiaH2aVsH2bRoute
  GuiaSalarioH2aRoute: typeof GuiaSalarioH2aRoute
  GuiaVistoH2bRoute: typeof GuiaVistoH2bRoute
  PrecosRoute: typeof PrecosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  VSlugRoute: typeof VSlugRoute
  VagasH2aStateRoute: typeof VagasH2aStateRoute
  VagasH2aColheitaLaranjaRoute: typeof VagasH2aColheitaLaranjaRoute
  VagasH2aColheitaMacaRoute: typeof VagasH2aColheitaMacaRoute
  VagasH2aEmpresasRoute: typeof VagasH2aEmpresasRoute
  VagasH2aTabacoRoute: typeof VagasH2aTabacoRoute
  VagasH2aIndexRoute: typeof VagasH2aIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCheckRepliesRoute: typeof ApiPublicHooksCheckRepliesRoute
  ApiPublicHooksImportDolFeedRoute: typeof ApiPublicHooksImportDolFeedRoute
  ApiPublicHooksSeoScanRoute: typeof ApiPublicHooksSeoScanRoute
  ApiPublicHooksSpikeAlertRoute: typeof ApiPublicHooksSpikeAlertRoute
  ApiPublicHooksUptimeRoute: typeof ApiPublicHooksUptimeRoute
  ApiPublicHooksVisaRemindersRoute: typeof ApiPublicHooksVisaRemindersRoute
  ApiPublicPaymentsDevSelftestRoute: typeof ApiPublicPaymentsDevSelftestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-visto-h2b': {
      id: '/guia-visto-h2b'
      path: '/guia-visto-h2b'
      fullPath: '/guia-visto-h2b'
      preLoaderRoute: typeof GuiaVistoH2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-salario-h2a': {
      id: '/guia-salario-h2a'
      path: '/guia-salario-h2a'
      fullPath: '/guia-salario-h2a'
      preLoaderRoute: typeof GuiaSalarioH2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-h2a-vs-h2b': {
      id: '/guia-h2a-vs-h2b'
      path: '/guia-h2a-vs-h2b'
      fullPath: '/guia-h2a-vs-h2b'
      preLoaderRoute: typeof GuiaH2aVsH2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-golpes-h2a': {
      id: '/guia-golpes-h2a'
      path: '/guia-golpes-h2a'
      fullPath: '/guia-golpes-h2a'
      preLoaderRoute: typeof GuiaGolpesH2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-entrevista-visto-h2a': {
      id: '/guia-entrevista-visto-h2a'
      path: '/guia-entrevista-visto-h2a'
      fullPath: '/guia-entrevista-visto-h2a'
      preLoaderRoute: typeof GuiaEntrevistaVistoH2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-ds160-visto-h2a': {
      id: '/guia-ds160-visto-h2a'
      path: '/guia-ds160-visto-h2a'
      fullPath: '/guia-ds160-visto-h2a'
      preLoaderRoute: typeof GuiaDs160VistoH2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-custos-visto-h2a': {
      id: '/guia-custos-visto-h2a'
      path: '/guia-custos-visto-h2a'
      fullPath: '/guia-custos-visto-h2a'
      preLoaderRoute: typeof GuiaCustosVistoH2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabalhar-nos-eua-legalmente': {
      id: '/como-trabalhar-nos-eua-legalmente'
      path: '/como-trabalhar-nos-eua-legalmente'
      fullPath: '/como-trabalhar-nos-eua-legalmente'
      preLoaderRoute: typeof ComoTrabalharNosEuaLegalmenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/': {
      id: '/vagas-h2a/'
      path: '/vagas-h2a'
      fullPath: '/vagas-h2a/'
      preLoaderRoute: typeof VagasH2aIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/tabaco': {
      id: '/vagas-h2a/tabaco'
      path: '/vagas-h2a/tabaco'
      fullPath: '/vagas-h2a/tabaco'
      preLoaderRoute: typeof VagasH2aTabacoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/empresas': {
      id: '/vagas-h2a/empresas'
      path: '/vagas-h2a/empresas'
      fullPath: '/vagas-h2a/empresas'
      preLoaderRoute: typeof VagasH2aEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/colheita-maca': {
      id: '/vagas-h2a/colheita-maca'
      path: '/vagas-h2a/colheita-maca'
      fullPath: '/vagas-h2a/colheita-maca'
      preLoaderRoute: typeof VagasH2aColheitaMacaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/colheita-laranja': {
      id: '/vagas-h2a/colheita-laranja'
      path: '/vagas-h2a/colheita-laranja'
      fullPath: '/vagas-h2a/colheita-laranja'
      preLoaderRoute: typeof VagasH2aColheitaLaranjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/$state': {
      id: '/vagas-h2a/$state'
      path: '/vagas-h2a/$state'
      fullPath: '/vagas-h2a/$state'
      preLoaderRoute: typeof VagasH2aStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/visto': {
      id: '/_authenticated/app/visto'
      path: '/app/visto'
      fullPath: '/app/visto'
      preLoaderRoute: typeof AuthenticatedAppVistoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/video': {
      id: '/_authenticated/app/video'
      path: '/app/video'
      fullPath: '/app/video'
      preLoaderRoute: typeof AuthenticatedAppVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/vagas': {
      id: '/_authenticated/app/vagas'
      path: '/app/vagas'
      fullPath: '/app/vagas'
      preLoaderRoute: typeof AuthenticatedAppVagasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/midia': {
      id: '/_authenticated/app/midia'
      path: '/app/midia'
      fullPath: '/app/midia'
      preLoaderRoute: typeof AuthenticatedAppMidiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ingles': {
      id: '/_authenticated/app/ingles'
      path: '/app/ingles'
      fullPath: '/app/ingles'
      preLoaderRoute: typeof AuthenticatedAppInglesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/followups': {
      id: '/_authenticated/app/followups'
      path: '/app/followups'
      fullPath: '/app/followups'
      preLoaderRoute: typeof AuthenticatedAppFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empregadores': {
      id: '/_authenticated/app/empregadores'
      path: '/app/empregadores'
      fullPath: '/app/empregadores'
      preLoaderRoute: typeof AuthenticatedAppEmpregadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/curriculos': {
      id: '/_authenticated/app/curriculos'
      path: '/app/curriculos'
      fullPath: '/app/curriculos'
      preLoaderRoute: typeof AuthenticatedAppCurriculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/curriculo': {
      id: '/_authenticated/app/curriculo'
      path: '/app/curriculo'
      fullPath: '/app/curriculo'
      preLoaderRoute: typeof AuthenticatedAppCurriculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/comecar': {
      id: '/_authenticated/app/comecar'
      path: '/app/comecar'
      fullPath: '/app/comecar'
      preLoaderRoute: typeof AuthenticatedAppComecarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/candidaturas': {
      id: '/_authenticated/app/candidaturas'
      path: '/app/candidaturas'
      fullPath: '/app/candidaturas'
      preLoaderRoute: typeof AuthenticatedAppCandidaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/auditoria': {
      id: '/_authenticated/app/auditoria'
      path: '/app/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/security': {
      id: '/_authenticated/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AuthenticatedAdminSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pro-features': {
      id: '/_authenticated/admin/pro-features'
      path: '/admin/pro-features'
      fullPath: '/admin/pro-features'
      preLoaderRoute: typeof AuthenticatedAdminProFeaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ingles/': {
      id: '/_authenticated/app/ingles/'
      path: '/'
      fullPath: '/app/ingles/'
      preLoaderRoute: typeof AuthenticatedAppInglesIndexRouteImport
      parentRoute: typeof AuthenticatedAppInglesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/dev-selftest': {
      id: '/api/public/payments/dev-selftest'
      path: '/api/public/payments/dev-selftest'
      fullPath: '/api/public/payments/dev-selftest'
      preLoaderRoute: typeof ApiPublicPaymentsDevSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/visa-reminders': {
      id: '/api/public/hooks/visa-reminders'
      path: '/api/public/hooks/visa-reminders'
      fullPath: '/api/public/hooks/visa-reminders'
      preLoaderRoute: typeof ApiPublicHooksVisaRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/uptime': {
      id: '/api/public/hooks/uptime'
      path: '/api/public/hooks/uptime'
      fullPath: '/api/public/hooks/uptime'
      preLoaderRoute: typeof ApiPublicHooksUptimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/spike-alert': {
      id: '/api/public/hooks/spike-alert'
      path: '/api/public/hooks/spike-alert'
      fullPath: '/api/public/hooks/spike-alert'
      preLoaderRoute: typeof ApiPublicHooksSpikeAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/seo-scan': {
      id: '/api/public/hooks/seo-scan'
      path: '/api/public/hooks/seo-scan'
      fullPath: '/api/public/hooks/seo-scan'
      preLoaderRoute: typeof ApiPublicHooksSeoScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-dol-feed': {
      id: '/api/public/hooks/import-dol-feed'
      path: '/api/public/hooks/import-dol-feed'
      fullPath: '/api/public/hooks/import-dol-feed'
      preLoaderRoute: typeof ApiPublicHooksImportDolFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-replies': {
      id: '/api/public/hooks/check-replies'
      path: '/api/public/hooks/check-replies'
      fullPath: '/api/public/hooks/check-replies'
      preLoaderRoute: typeof ApiPublicHooksCheckRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/visto/historico': {
      id: '/_authenticated/app/visto/historico'
      path: '/historico'
      fullPath: '/app/visto/historico'
      preLoaderRoute: typeof AuthenticatedAppVistoHistoricoRouteImport
      parentRoute: typeof AuthenticatedAppVistoRoute
    }
    '/_authenticated/app/ingles/$module': {
      id: '/_authenticated/app/ingles/$module'
      path: '/$module'
      fullPath: '/app/ingles/$module'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleRouteImport
      parentRoute: typeof AuthenticatedAppInglesRoute
    }
    '/_authenticated/app/admin/emails': {
      id: '/_authenticated/app/admin/emails'
      path: '/app/admin/emails'
      fullPath: '/app/admin/emails'
      preLoaderRoute: typeof AuthenticatedAppAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ingles/$module/': {
      id: '/_authenticated/app/ingles/$module/'
      path: '/'
      fullPath: '/app/ingles/$module/'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleIndexRouteImport
      parentRoute: typeof AuthenticatedAppInglesModuleRoute
    }
    '/_authenticated/app/ingles/$module/$lesson': {
      id: '/_authenticated/app/ingles/$module/$lesson'
      path: '/$lesson'
      fullPath: '/app/ingles/$module/$lesson'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleLessonRouteImport
      parentRoute: typeof AuthenticatedAppInglesModuleRoute
    }
    '/_authenticated/app/admin/emails/preview': {
      id: '/_authenticated/app/admin/emails/preview'
      path: '/preview'
      fullPath: '/app/admin/emails/preview'
      preLoaderRoute: typeof AuthenticatedAppAdminEmailsPreviewRouteImport
      parentRoute: typeof AuthenticatedAppAdminEmailsRoute
    }
  }
}

interface AuthenticatedAppInglesModuleRouteChildren {
  AuthenticatedAppInglesModuleLessonRoute: typeof AuthenticatedAppInglesModuleLessonRoute
  AuthenticatedAppInglesModuleIndexRoute: typeof AuthenticatedAppInglesModuleIndexRoute
}

const AuthenticatedAppInglesModuleRouteChildren: AuthenticatedAppInglesModuleRouteChildren =
  {
    AuthenticatedAppInglesModuleLessonRoute:
      AuthenticatedAppInglesModuleLessonRoute,
    AuthenticatedAppInglesModuleIndexRoute:
      AuthenticatedAppInglesModuleIndexRoute,
  }

const AuthenticatedAppInglesModuleRouteWithChildren =
  AuthenticatedAppInglesModuleRoute._addFileChildren(
    AuthenticatedAppInglesModuleRouteChildren,
  )

interface AuthenticatedAppInglesRouteChildren {
  AuthenticatedAppInglesModuleRoute: typeof AuthenticatedAppInglesModuleRouteWithChildren
  AuthenticatedAppInglesIndexRoute: typeof AuthenticatedAppInglesIndexRoute
}

const AuthenticatedAppInglesRouteChildren: AuthenticatedAppInglesRouteChildren =
  {
    AuthenticatedAppInglesModuleRoute:
      AuthenticatedAppInglesModuleRouteWithChildren,
    AuthenticatedAppInglesIndexRoute: AuthenticatedAppInglesIndexRoute,
  }

const AuthenticatedAppInglesRouteWithChildren =
  AuthenticatedAppInglesRoute._addFileChildren(
    AuthenticatedAppInglesRouteChildren,
  )

interface AuthenticatedAppVistoRouteChildren {
  AuthenticatedAppVistoHistoricoRoute: typeof AuthenticatedAppVistoHistoricoRoute
}

const AuthenticatedAppVistoRouteChildren: AuthenticatedAppVistoRouteChildren = {
  AuthenticatedAppVistoHistoricoRoute: AuthenticatedAppVistoHistoricoRoute,
}

const AuthenticatedAppVistoRouteWithChildren =
  AuthenticatedAppVistoRoute._addFileChildren(
    AuthenticatedAppVistoRouteChildren,
  )

interface AuthenticatedAppAdminEmailsRouteChildren {
  AuthenticatedAppAdminEmailsPreviewRoute: typeof AuthenticatedAppAdminEmailsPreviewRoute
}

const AuthenticatedAppAdminEmailsRouteChildren: AuthenticatedAppAdminEmailsRouteChildren =
  {
    AuthenticatedAppAdminEmailsPreviewRoute:
      AuthenticatedAppAdminEmailsPreviewRoute,
  }

const AuthenticatedAppAdminEmailsRouteWithChildren =
  AuthenticatedAppAdminEmailsRoute._addFileChildren(
    AuthenticatedAppAdminEmailsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminProFeaturesRoute: typeof AuthenticatedAdminProFeaturesRoute
  AuthenticatedAdminSecurityRoute: typeof AuthenticatedAdminSecurityRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAppAuditoriaRoute: typeof AuthenticatedAppAuditoriaRoute
  AuthenticatedAppCandidaturasRoute: typeof AuthenticatedAppCandidaturasRoute
  AuthenticatedAppComecarRoute: typeof AuthenticatedAppComecarRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppCurriculoRoute: typeof AuthenticatedAppCurriculoRoute
  AuthenticatedAppCurriculosRoute: typeof AuthenticatedAppCurriculosRoute
  AuthenticatedAppEmpregadoresRoute: typeof AuthenticatedAppEmpregadoresRoute
  AuthenticatedAppFollowupsRoute: typeof AuthenticatedAppFollowupsRoute
  AuthenticatedAppInglesRoute: typeof AuthenticatedAppInglesRouteWithChildren
  AuthenticatedAppMidiaRoute: typeof AuthenticatedAppMidiaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppVagasRoute: typeof AuthenticatedAppVagasRoute
  AuthenticatedAppVideoRoute: typeof AuthenticatedAppVideoRoute
  AuthenticatedAppVistoRoute: typeof AuthenticatedAppVistoRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminEmailsRoute: typeof AuthenticatedAppAdminEmailsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminProFeaturesRoute: AuthenticatedAdminProFeaturesRoute,
  AuthenticatedAdminSecurityRoute: AuthenticatedAdminSecurityRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAppAuditoriaRoute: AuthenticatedAppAuditoriaRoute,
  AuthenticatedAppCandidaturasRoute: AuthenticatedAppCandidaturasRoute,
  AuthenticatedAppComecarRoute: AuthenticatedAppComecarRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppCurriculoRoute: AuthenticatedAppCurriculoRoute,
  AuthenticatedAppCurriculosRoute: AuthenticatedAppCurriculosRoute,
  AuthenticatedAppEmpregadoresRoute: AuthenticatedAppEmpregadoresRoute,
  AuthenticatedAppFollowupsRoute: AuthenticatedAppFollowupsRoute,
  AuthenticatedAppInglesRoute: AuthenticatedAppInglesRouteWithChildren,
  AuthenticatedAppMidiaRoute: AuthenticatedAppMidiaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppVagasRoute: AuthenticatedAppVagasRoute,
  AuthenticatedAppVideoRoute: AuthenticatedAppVideoRoute,
  AuthenticatedAppVistoRoute: AuthenticatedAppVistoRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminEmailsRoute:
    AuthenticatedAppAdminEmailsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ComoTrabalharNosEuaLegalmenteRoute: ComoTrabalharNosEuaLegalmenteRoute,
  GuiaCustosVistoH2aRoute: GuiaCustosVistoH2aRoute,
  GuiaDs160VistoH2aRoute: GuiaDs160VistoH2aRoute,
  GuiaEntrevistaVistoH2aRoute: GuiaEntrevistaVistoH2aRoute,
  GuiaGolpesH2aRoute: GuiaGolpesH2aRoute,
  GuiaH2aVsH2bRoute: GuiaH2aVsH2bRoute,
  GuiaSalarioH2aRoute: GuiaSalarioH2aRoute,
  GuiaVistoH2bRoute: GuiaVistoH2bRoute,
  PrecosRoute: PrecosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  VSlugRoute: VSlugRoute,
  VagasH2aStateRoute: VagasH2aStateRoute,
  VagasH2aColheitaLaranjaRoute: VagasH2aColheitaLaranjaRoute,
  VagasH2aColheitaMacaRoute: VagasH2aColheitaMacaRoute,
  VagasH2aEmpresasRoute: VagasH2aEmpresasRoute,
  VagasH2aTabacoRoute: VagasH2aTabacoRoute,
  VagasH2aIndexRoute: VagasH2aIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCheckRepliesRoute: ApiPublicHooksCheckRepliesRoute,
  ApiPublicHooksImportDolFeedRoute: ApiPublicHooksImportDolFeedRoute,
  ApiPublicHooksSeoScanRoute: ApiPublicHooksSeoScanRoute,
  ApiPublicHooksSpikeAlertRoute: ApiPublicHooksSpikeAlertRoute,
  ApiPublicHooksUptimeRoute: ApiPublicHooksUptimeRoute,
  ApiPublicHooksVisaRemindersRoute: ApiPublicHooksVisaRemindersRoute,
  ApiPublicPaymentsDevSelftestRoute: ApiPublicPaymentsDevSelftestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
