/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasH2aIndexRouteImport } from './routes/vagas-h2a.index'
import { Route as VagasH2aStateRouteImport } from './routes/vagas-h2a.$state'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicSeedEnglishRouteImport } from './routes/api/public/seed-english'
import { Route as AuthenticatedAppVistoRouteImport } from './routes/_authenticated/app.visto'
import { Route as AuthenticatedAppVideoRouteImport } from './routes/_authenticated/app.video'
import { Route as AuthenticatedAppVagasRouteImport } from './routes/_authenticated/app.vagas'
import { Route as AuthenticatedAppPerfilRouteImport } from './routes/_authenticated/app.perfil'
import { Route as AuthenticatedAppMidiaRouteImport } from './routes/_authenticated/app.midia'
import { Route as AuthenticatedAppInglesRouteImport } from './routes/_authenticated/app.ingles'
import { Route as AuthenticatedAppFollowupsRouteImport } from './routes/_authenticated/app.followups'
import { Route as AuthenticatedAppEmpregadoresRouteImport } from './routes/_authenticated/app.empregadores'
import { Route as AuthenticatedAppCurriculoRouteImport } from './routes/_authenticated/app.curriculo'
import { Route as AuthenticatedAppComecarRouteImport } from './routes/_authenticated/app.comecar'
import { Route as AuthenticatedAppCandidaturasRouteImport } from './routes/_authenticated/app.candidaturas'
import { Route as AuthenticatedAppInglesIndexRouteImport } from './routes/_authenticated/app.ingles.index'
import { Route as ApiPublicHooksImportDolFeedRouteImport } from './routes/api/public/hooks/import-dol-feed'
import { Route as ApiPublicHooksCheckRepliesRouteImport } from './routes/api/public/hooks/check-replies'
import { Route as AuthenticatedAppInglesModuleRouteImport } from './routes/_authenticated/app.ingles.$module'
import { Route as AuthenticatedAppInglesModuleIndexRouteImport } from './routes/_authenticated/app.ingles.$module.index'
import { Route as AuthenticatedAppInglesModuleLessonRouteImport } from './routes/_authenticated/app.ingles.$module.$lesson'

const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aIndexRoute = VagasH2aIndexRouteImport.update({
  id: '/vagas-h2a/',
  path: '/vagas-h2a/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasH2aStateRoute = VagasH2aStateRouteImport.update({
  id: '/vagas-h2a/$state',
  path: '/vagas-h2a/$state',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSeedEnglishRoute = ApiPublicSeedEnglishRouteImport.update({
  id: '/api/public/seed-english',
  path: '/api/public/seed-english',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppVistoRoute = AuthenticatedAppVistoRouteImport.update({
  id: '/app/visto',
  path: '/app/visto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVideoRoute = AuthenticatedAppVideoRouteImport.update({
  id: '/app/video',
  path: '/app/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppVagasRoute = AuthenticatedAppVagasRouteImport.update({
  id: '/app/vagas',
  path: '/app/vagas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPerfilRoute = AuthenticatedAppPerfilRouteImport.update({
  id: '/app/perfil',
  path: '/app/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMidiaRoute = AuthenticatedAppMidiaRouteImport.update({
  id: '/app/midia',
  path: '/app/midia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppInglesRoute = AuthenticatedAppInglesRouteImport.update({
  id: '/app/ingles',
  path: '/app/ingles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFollowupsRoute =
  AuthenticatedAppFollowupsRouteImport.update({
    id: '/app/followups',
    path: '/app/followups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppEmpregadoresRoute =
  AuthenticatedAppEmpregadoresRouteImport.update({
    id: '/app/empregadores',
    path: '/app/empregadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCurriculoRoute =
  AuthenticatedAppCurriculoRouteImport.update({
    id: '/app/curriculo',
    path: '/app/curriculo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppComecarRoute = AuthenticatedAppComecarRouteImport.update({
  id: '/app/comecar',
  path: '/app/comecar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCandidaturasRoute =
  AuthenticatedAppCandidaturasRouteImport.update({
    id: '/app/candidaturas',
    path: '/app/candidaturas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInglesIndexRoute =
  AuthenticatedAppInglesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInglesRoute,
  } as any)
const ApiPublicHooksImportDolFeedRoute =
  ApiPublicHooksImportDolFeedRouteImport.update({
    id: '/api/public/hooks/import-dol-feed',
    path: '/api/public/hooks/import-dol-feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCheckRepliesRoute =
  ApiPublicHooksCheckRepliesRouteImport.update({
    id: '/api/public/hooks/check-replies',
    path: '/api/public/hooks/check-replies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppInglesModuleRoute =
  AuthenticatedAppInglesModuleRouteImport.update({
    id: '/$module',
    path: '/$module',
    getParentRoute: () => AuthenticatedAppInglesRoute,
  } as any)
const AuthenticatedAppInglesModuleIndexRoute =
  AuthenticatedAppInglesModuleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInglesModuleRoute,
  } as any)
const AuthenticatedAppInglesModuleLessonRoute =
  AuthenticatedAppInglesModuleLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => AuthenticatedAppInglesModuleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a/': typeof VagasH2aIndexRoute
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/comecar': typeof AuthenticatedAppComecarRoute
  '/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/ingles': typeof AuthenticatedAppInglesRouteWithChildren
  '/app/midia': typeof AuthenticatedAppMidiaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app/video': typeof AuthenticatedAppVideoRoute
  '/app/visto': typeof AuthenticatedAppVistoRoute
  '/api/public/seed-english': typeof ApiPublicSeedEnglishRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/ingles/$module': typeof AuthenticatedAppInglesModuleRouteWithChildren
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/app/ingles/': typeof AuthenticatedAppInglesIndexRoute
  '/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/app/ingles/$module/': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a': typeof VagasH2aIndexRoute
  '/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/app/comecar': typeof AuthenticatedAppComecarRoute
  '/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/app/midia': typeof AuthenticatedAppMidiaRoute
  '/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/app/vagas': typeof AuthenticatedAppVagasRoute
  '/app/video': typeof AuthenticatedAppVideoRoute
  '/app/visto': typeof AuthenticatedAppVistoRoute
  '/api/public/seed-english': typeof ApiPublicSeedEnglishRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/app/ingles': typeof AuthenticatedAppInglesIndexRoute
  '/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/app/ingles/$module': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/precos': typeof PrecosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/v/$slug': typeof VSlugRoute
  '/vagas-h2a/$state': typeof VagasH2aStateRoute
  '/vagas-h2a/': typeof VagasH2aIndexRoute
  '/_authenticated/app/candidaturas': typeof AuthenticatedAppCandidaturasRoute
  '/_authenticated/app/comecar': typeof AuthenticatedAppComecarRoute
  '/_authenticated/app/curriculo': typeof AuthenticatedAppCurriculoRoute
  '/_authenticated/app/empregadores': typeof AuthenticatedAppEmpregadoresRoute
  '/_authenticated/app/followups': typeof AuthenticatedAppFollowupsRoute
  '/_authenticated/app/ingles': typeof AuthenticatedAppInglesRouteWithChildren
  '/_authenticated/app/midia': typeof AuthenticatedAppMidiaRoute
  '/_authenticated/app/perfil': typeof AuthenticatedAppPerfilRoute
  '/_authenticated/app/vagas': typeof AuthenticatedAppVagasRoute
  '/_authenticated/app/video': typeof AuthenticatedAppVideoRoute
  '/_authenticated/app/visto': typeof AuthenticatedAppVistoRoute
  '/api/public/seed-english': typeof ApiPublicSeedEnglishRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/ingles/$module': typeof AuthenticatedAppInglesModuleRouteWithChildren
  '/api/public/hooks/check-replies': typeof ApiPublicHooksCheckRepliesRoute
  '/api/public/hooks/import-dol-feed': typeof ApiPublicHooksImportDolFeedRoute
  '/_authenticated/app/ingles/': typeof AuthenticatedAppInglesIndexRoute
  '/_authenticated/app/ingles/$module/$lesson': typeof AuthenticatedAppInglesModuleLessonRoute
  '/_authenticated/app/ingles/$module/': typeof AuthenticatedAppInglesModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/precos'
    | '/checkout/return'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a/'
    | '/app/candidaturas'
    | '/app/comecar'
    | '/app/curriculo'
    | '/app/empregadores'
    | '/app/followups'
    | '/app/ingles'
    | '/app/midia'
    | '/app/perfil'
    | '/app/vagas'
    | '/app/video'
    | '/app/visto'
    | '/api/public/seed-english'
    | '/app/'
    | '/app/ingles/$module'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/app/ingles/'
    | '/app/ingles/$module/$lesson'
    | '/app/ingles/$module/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/precos'
    | '/checkout/return'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a'
    | '/app/candidaturas'
    | '/app/comecar'
    | '/app/curriculo'
    | '/app/empregadores'
    | '/app/followups'
    | '/app/midia'
    | '/app/perfil'
    | '/app/vagas'
    | '/app/video'
    | '/app/visto'
    | '/api/public/seed-english'
    | '/app'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/app/ingles'
    | '/app/ingles/$module/$lesson'
    | '/app/ingles/$module'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/precos'
    | '/checkout/return'
    | '/v/$slug'
    | '/vagas-h2a/$state'
    | '/vagas-h2a/'
    | '/_authenticated/app/candidaturas'
    | '/_authenticated/app/comecar'
    | '/_authenticated/app/curriculo'
    | '/_authenticated/app/empregadores'
    | '/_authenticated/app/followups'
    | '/_authenticated/app/ingles'
    | '/_authenticated/app/midia'
    | '/_authenticated/app/perfil'
    | '/_authenticated/app/vagas'
    | '/_authenticated/app/video'
    | '/_authenticated/app/visto'
    | '/api/public/seed-english'
    | '/_authenticated/app/'
    | '/_authenticated/app/ingles/$module'
    | '/api/public/hooks/check-replies'
    | '/api/public/hooks/import-dol-feed'
    | '/_authenticated/app/ingles/'
    | '/_authenticated/app/ingles/$module/$lesson'
    | '/_authenticated/app/ingles/$module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrecosRoute: typeof PrecosRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  VSlugRoute: typeof VSlugRoute
  VagasH2aStateRoute: typeof VagasH2aStateRoute
  VagasH2aIndexRoute: typeof VagasH2aIndexRoute
  ApiPublicSeedEnglishRoute: typeof ApiPublicSeedEnglishRoute
  ApiPublicHooksCheckRepliesRoute: typeof ApiPublicHooksCheckRepliesRoute
  ApiPublicHooksImportDolFeedRoute: typeof ApiPublicHooksImportDolFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/': {
      id: '/vagas-h2a/'
      path: '/vagas-h2a'
      fullPath: '/vagas-h2a/'
      preLoaderRoute: typeof VagasH2aIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas-h2a/$state': {
      id: '/vagas-h2a/$state'
      path: '/vagas-h2a/$state'
      fullPath: '/vagas-h2a/$state'
      preLoaderRoute: typeof VagasH2aStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/seed-english': {
      id: '/api/public/seed-english'
      path: '/api/public/seed-english'
      fullPath: '/api/public/seed-english'
      preLoaderRoute: typeof ApiPublicSeedEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/visto': {
      id: '/_authenticated/app/visto'
      path: '/app/visto'
      fullPath: '/app/visto'
      preLoaderRoute: typeof AuthenticatedAppVistoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/video': {
      id: '/_authenticated/app/video'
      path: '/app/video'
      fullPath: '/app/video'
      preLoaderRoute: typeof AuthenticatedAppVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/vagas': {
      id: '/_authenticated/app/vagas'
      path: '/app/vagas'
      fullPath: '/app/vagas'
      preLoaderRoute: typeof AuthenticatedAppVagasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/perfil': {
      id: '/_authenticated/app/perfil'
      path: '/app/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AuthenticatedAppPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/midia': {
      id: '/_authenticated/app/midia'
      path: '/app/midia'
      fullPath: '/app/midia'
      preLoaderRoute: typeof AuthenticatedAppMidiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ingles': {
      id: '/_authenticated/app/ingles'
      path: '/app/ingles'
      fullPath: '/app/ingles'
      preLoaderRoute: typeof AuthenticatedAppInglesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/followups': {
      id: '/_authenticated/app/followups'
      path: '/app/followups'
      fullPath: '/app/followups'
      preLoaderRoute: typeof AuthenticatedAppFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/empregadores': {
      id: '/_authenticated/app/empregadores'
      path: '/app/empregadores'
      fullPath: '/app/empregadores'
      preLoaderRoute: typeof AuthenticatedAppEmpregadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/curriculo': {
      id: '/_authenticated/app/curriculo'
      path: '/app/curriculo'
      fullPath: '/app/curriculo'
      preLoaderRoute: typeof AuthenticatedAppCurriculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/comecar': {
      id: '/_authenticated/app/comecar'
      path: '/app/comecar'
      fullPath: '/app/comecar'
      preLoaderRoute: typeof AuthenticatedAppComecarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/candidaturas': {
      id: '/_authenticated/app/candidaturas'
      path: '/app/candidaturas'
      fullPath: '/app/candidaturas'
      preLoaderRoute: typeof AuthenticatedAppCandidaturasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ingles/': {
      id: '/_authenticated/app/ingles/'
      path: '/'
      fullPath: '/app/ingles/'
      preLoaderRoute: typeof AuthenticatedAppInglesIndexRouteImport
      parentRoute: typeof AuthenticatedAppInglesRoute
    }
    '/api/public/hooks/import-dol-feed': {
      id: '/api/public/hooks/import-dol-feed'
      path: '/api/public/hooks/import-dol-feed'
      fullPath: '/api/public/hooks/import-dol-feed'
      preLoaderRoute: typeof ApiPublicHooksImportDolFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-replies': {
      id: '/api/public/hooks/check-replies'
      path: '/api/public/hooks/check-replies'
      fullPath: '/api/public/hooks/check-replies'
      preLoaderRoute: typeof ApiPublicHooksCheckRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ingles/$module': {
      id: '/_authenticated/app/ingles/$module'
      path: '/$module'
      fullPath: '/app/ingles/$module'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleRouteImport
      parentRoute: typeof AuthenticatedAppInglesRoute
    }
    '/_authenticated/app/ingles/$module/': {
      id: '/_authenticated/app/ingles/$module/'
      path: '/'
      fullPath: '/app/ingles/$module/'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleIndexRouteImport
      parentRoute: typeof AuthenticatedAppInglesModuleRoute
    }
    '/_authenticated/app/ingles/$module/$lesson': {
      id: '/_authenticated/app/ingles/$module/$lesson'
      path: '/$lesson'
      fullPath: '/app/ingles/$module/$lesson'
      preLoaderRoute: typeof AuthenticatedAppInglesModuleLessonRouteImport
      parentRoute: typeof AuthenticatedAppInglesModuleRoute
    }
  }
}

interface AuthenticatedAppInglesModuleRouteChildren {
  AuthenticatedAppInglesModuleLessonRoute: typeof AuthenticatedAppInglesModuleLessonRoute
  AuthenticatedAppInglesModuleIndexRoute: typeof AuthenticatedAppInglesModuleIndexRoute
}

const AuthenticatedAppInglesModuleRouteChildren: AuthenticatedAppInglesModuleRouteChildren =
  {
    AuthenticatedAppInglesModuleLessonRoute:
      AuthenticatedAppInglesModuleLessonRoute,
    AuthenticatedAppInglesModuleIndexRoute:
      AuthenticatedAppInglesModuleIndexRoute,
  }

const AuthenticatedAppInglesModuleRouteWithChildren =
  AuthenticatedAppInglesModuleRoute._addFileChildren(
    AuthenticatedAppInglesModuleRouteChildren,
  )

interface AuthenticatedAppInglesRouteChildren {
  AuthenticatedAppInglesModuleRoute: typeof AuthenticatedAppInglesModuleRouteWithChildren
  AuthenticatedAppInglesIndexRoute: typeof AuthenticatedAppInglesIndexRoute
}

const AuthenticatedAppInglesRouteChildren: AuthenticatedAppInglesRouteChildren =
  {
    AuthenticatedAppInglesModuleRoute:
      AuthenticatedAppInglesModuleRouteWithChildren,
    AuthenticatedAppInglesIndexRoute: AuthenticatedAppInglesIndexRoute,
  }

const AuthenticatedAppInglesRouteWithChildren =
  AuthenticatedAppInglesRoute._addFileChildren(
    AuthenticatedAppInglesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppCandidaturasRoute: typeof AuthenticatedAppCandidaturasRoute
  AuthenticatedAppComecarRoute: typeof AuthenticatedAppComecarRoute
  AuthenticatedAppCurriculoRoute: typeof AuthenticatedAppCurriculoRoute
  AuthenticatedAppEmpregadoresRoute: typeof AuthenticatedAppEmpregadoresRoute
  AuthenticatedAppFollowupsRoute: typeof AuthenticatedAppFollowupsRoute
  AuthenticatedAppInglesRoute: typeof AuthenticatedAppInglesRouteWithChildren
  AuthenticatedAppMidiaRoute: typeof AuthenticatedAppMidiaRoute
  AuthenticatedAppPerfilRoute: typeof AuthenticatedAppPerfilRoute
  AuthenticatedAppVagasRoute: typeof AuthenticatedAppVagasRoute
  AuthenticatedAppVideoRoute: typeof AuthenticatedAppVideoRoute
  AuthenticatedAppVistoRoute: typeof AuthenticatedAppVistoRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppCandidaturasRoute: AuthenticatedAppCandidaturasRoute,
  AuthenticatedAppComecarRoute: AuthenticatedAppComecarRoute,
  AuthenticatedAppCurriculoRoute: AuthenticatedAppCurriculoRoute,
  AuthenticatedAppEmpregadoresRoute: AuthenticatedAppEmpregadoresRoute,
  AuthenticatedAppFollowupsRoute: AuthenticatedAppFollowupsRoute,
  AuthenticatedAppInglesRoute: AuthenticatedAppInglesRouteWithChildren,
  AuthenticatedAppMidiaRoute: AuthenticatedAppMidiaRoute,
  AuthenticatedAppPerfilRoute: AuthenticatedAppPerfilRoute,
  AuthenticatedAppVagasRoute: AuthenticatedAppVagasRoute,
  AuthenticatedAppVideoRoute: AuthenticatedAppVideoRoute,
  AuthenticatedAppVistoRoute: AuthenticatedAppVistoRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrecosRoute: PrecosRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  VSlugRoute: VSlugRoute,
  VagasH2aStateRoute: VagasH2aStateRoute,
  VagasH2aIndexRoute: VagasH2aIndexRoute,
  ApiPublicSeedEnglishRoute: ApiPublicSeedEnglishRoute,
  ApiPublicHooksCheckRepliesRoute: ApiPublicHooksCheckRepliesRoute,
  ApiPublicHooksImportDolFeedRoute: ApiPublicHooksImportDolFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
